package milestonecalculator;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JOptionPane;

public class CalculatorJFrame extends javax.swing.JFrame {
    

    /**
     * Creates new form CalculatorJFrame
     */
    public CalculatorJFrame() {
        initComponents();
        clearButton.addActionListener(this::clearButtonActionPerformed);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        milestoneOneLabel = new javax.swing.JLabel();
        milestoneTwoLabel = new javax.swing.JLabel();
        TALabel = new javax.swing.JLabel();
        ms1TF = new javax.swing.JTextField();
        ms2TF = new javax.swing.JTextField();
        taTF = new javax.swing.JTextField();
        labelPicTF = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        gradeLabel1 = new javax.swing.JLabel();
        gradeTF1 = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 204, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        milestoneOneLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 12)); // NOI18N
        milestoneOneLabel.setText("Milestone One");

        milestoneTwoLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 12)); // NOI18N
        milestoneTwoLabel.setText("Milestone Two");

        TALabel.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 12)); // NOI18N
        TALabel.setText("Terminal Assessment");

        ms1TF.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ms1TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ms2TF.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ms2TF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        taTF.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        taTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        taTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taTFActionPerformed(evt);
            }
        });

        labelPicTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelPicTF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milestonecalculator/logo.png"))); // NOI18N
        labelPicTF.setPreferredSize(new java.awt.Dimension(120, 90));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(milestoneTwoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(milestoneOneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TALabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ms2TF, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(ms1TF)
                            .addComponent(taTF))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPicTF, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(114, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(milestoneOneLabel)
                    .addComponent(ms1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(milestoneTwoLabel)
                    .addComponent(ms2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TALabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPicTF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        headerLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(0, 0, 153));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("MMDC Milestone Calculator");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totalLabel.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 12)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalLabel.setText("Total");

        totalTF.setBackground(new java.awt.Color(255, 255, 255));
        totalTF.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        totalTF.setForeground(new java.awt.Color(204, 0, 0));
        totalTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalTF.setBorder(null);
        totalTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTFActionPerformed(evt);
            }
        });

        gradeLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 12)); // NOI18N
        gradeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gradeLabel1.setText("Grade");

        gradeTF1.setBackground(new java.awt.Color(255, 255, 255));
        gradeTF1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        gradeTF1.setForeground(new java.awt.Color(204, 0, 0));
        gradeTF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gradeTF1.setBorder(null);
        gradeTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeTF1ActionPerformed(evt);
            }
        });

        calculateButton.setBackground(new java.awt.Color(153, 153, 255));
        calculateButton.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        calculateButton.setForeground(new java.awt.Color(0, 0, 204));
        calculateButton.setText("Calculate");
        calculateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(153, 153, 255));
        clearButton.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        clearButton.setForeground(new java.awt.Color(0, 0, 204));
        clearButton.setText("Clear");
        clearButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradeLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradeTF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gradeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradeTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taTFActionPerformed

    private void totalTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTFActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
 
         // Retrieve input scores
        String milestoneOneScore = ms1TF.getText();
        String milestoneTwoScore = ms2TF.getText();
        String TAScore = taTF.getText();

    try {
        // Convert input scores to doubles
        double milestoneOne = Double.parseDouble(milestoneOneScore);
        double milestoneTwo = Double.parseDouble(milestoneTwoScore);
        double TA = Double.parseDouble(TAScore);

        // Define maximum points for each component
        double maxMs1 = 25;
        double maxMs2 = 40;
        double maxTA = 35;

        // Check if input scores are within valid range
        if (milestoneOne < 0 || milestoneOne > maxMs1 || 
            milestoneTwo < 0 || milestoneTwo > maxMs2 || 
            TA < 0 || TA > maxTA) {
            throw new IllegalArgumentException("Invalid score entered. MS1 = n/25 | MS2 = n/40 | TA = n/35");
        }

        // Calculate weighted scores
        double weightedMs1 = ((milestoneOne / maxMs1 ) * 25);
        double weightedMs2 = ((milestoneTwo / maxMs2 ) * 40);
        double weightedTA = ((TA / maxTA ) * 35);

        // Calculate overall score
        double overallScore = weightedMs1 + weightedMs2 + weightedTA;

        // Display overall score with two decimal places
        totalTF.setText(String.format("%.2f", overallScore));

        // Determine and display grade based on overall score
        if (overallScore > 96) {
            gradeTF1.setText("1.00");
        } else if (overallScore <= 96 && overallScore >= 91.51) {
            gradeTF1.setText("1.25");
        } else if (overallScore <= 91.50 && overallScore >= 87.01) {
            gradeTF1.setText("1.50");
        } else if (overallScore <= 87.00 && overallScore >= 82.51) {
            gradeTF1.setText("1.75");
        } else if (overallScore <= 82.50 && overallScore >= 78.01) {
            gradeTF1.setText("2.00");
        } else if (overallScore <= 78.00 && overallScore >= 73.51) {
            gradeTF1.setText("2.25");
        } else if (overallScore <= 73.50 && overallScore >= 69.01) {
            gradeTF1.setText("2.50");
        } else if (overallScore <= 69.00 && overallScore >= 64.51) {
            gradeTF1.setText("2.75");
        } else if (overallScore <= 64.50 && overallScore >= 60.00) {
            gradeTF1.setText("3.00");
        } else if (overallScore < 60.00 && overallScore > 0.00) {
            gradeTF1.setText("3.00");
        } else if (overallScore == 0.00) {
            gradeTF1.setText("Failed");
        }
    } catch (NumberFormatException e) {
        // Handle non-numeric input
        JOptionPane.showMessageDialog(this, "Please enter valid numeric scores.");
    } catch (IllegalArgumentException e) {
        // Handle invalid score range
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
         
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void gradeTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeTF1ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // Reset text fields
        ms1TF.setText("");
        ms2TF.setText("");
        taTF.setText("");
        totalTF.setText("");
        gradeTF1.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TALabel;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel gradeLabel1;
    private javax.swing.JTextField gradeTF1;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelPicTF;
    private javax.swing.JLabel milestoneOneLabel;
    private javax.swing.JLabel milestoneTwoLabel;
    private javax.swing.JTextField ms1TF;
    private javax.swing.JTextField ms2TF;
    private javax.swing.JTextField taTF;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
